name: "DomBusGateway"
description: "DomBus to MQTT-AD bridge: use Creasol DomBus inputs/outputs/sensors modules"
slug: "dombusgateway"
version: "0.0.14"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

url: "https://github.com/creasoltech/dombusgateway"

apparmor: false

startup: services


ports:
  8023/tcp: 8023

host_serial: true
uart: true

devices:
  - /dev/ttyUSB0  
  
#logger:
#  logs:
#    info_log: data/info.log

# Options that the user can configure in the UI
options:
  
  debug_level: 7
  bus1_port: "/dev/ttyUSB0"
  mqtt_host: "homeassistant.local"
  mqtt_port: 1883
  mqtt_user: "dombus"
  mqtt_pass: "secretpasswd"


# Schema defines the format for the options above. This creates a form in the UI.
schema:
  debug_level: int
  bus1_port: str
  bus2_port: "str?"
  bus3_port: "str?"
  bus4_port: "str?"
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_pass: str

## Not mandatory but good practice: Document the secrets
#secrets:
#  - mqtt_username
#  - mqtt_password    

image: "ghcr.io/creasoltech/{arch}-dombusgateway-addon"
